### ISSUE TITLE
Duplicate question bug

### ISSUE THREAD

**Issue by forzaz** [forzaz/Mobile-Experience-Sampling-Master#21]
There was a bug that when users do the survey multiple times offline, questions in the SQLite are duplicated because no delete function was in the offline mode.

I have fixed it myself by moving the delete function from retrieveQuestionOnline to renderQuestion, so it applies to both online and offline.

**Comment by mmamarmarc** [comment]
You are indeed right, there was something wrong in the logic.
I changed it a bit different though as it had to be downloaded on logging in as well.
